force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donation</label>
    <nameField>
        <label>Donation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>MID(DateTime__c, 0, 10)</formula>
    <label>Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <label>DateTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DonationsController.cls
public with sharing class DonationsController {

    @AuraEnabled(cacheable=true)
    public static List<Donations__c> getRecords(){
        List<Donations__c> donations = [
            SELECT Id, DateTime__c, Date__c, Description__c, Amount__c
            FROM Donations__c
            WHERE Description__c != 'Від: Олесь Матюшенко'
                AND Description__c != 'Від: Наталія Матюшенко'
                AND Description__c != 'З чорної картки'
            LIMIT 200];
        return donations;
    }
}